/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as prestigeDocsUseThemeReferenceRouteImport } from './routes/(prestige)/docs.use-theme-reference'
import { Route as prestigeDocsThemeProviderReferenceRouteImport } from './routes/(prestige)/docs.theme-provider-reference'
import { Route as prestigeDocsTailwindRouteImport } from './routes/(prestige)/docs.tailwind'
import { Route as prestigeDocsStorageRouteImport } from './routes/(prestige)/docs.storage'
import { Route as prestigeDocsMultiThemingRouteImport } from './routes/(prestige)/docs.multi-theming'
import { Route as prestigeDocsHydrationRouteImport } from './routes/(prestige)/docs.hydration'
import { Route as prestigeDocsGetStartedRouteImport } from './routes/(prestige)/docs.get-started'

const prestigeDocsLazyRouteImport = createFileRoute('/(prestige)/docs')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const prestigeDocsLazyRoute = prestigeDocsLazyRouteImport
  .update({
    id: '/(prestige)/docs',
    path: '/docs',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(prestige)/docs.lazy').then((d) => d.Route))
const prestigeDocsUseThemeReferenceRoute =
  prestigeDocsUseThemeReferenceRouteImport
    .update({
      id: '/use-theme-reference',
      path: '/use-theme-reference',
      getParentRoute: () => prestigeDocsLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/docs.use-theme-reference.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeDocsThemeProviderReferenceRoute =
  prestigeDocsThemeProviderReferenceRouteImport
    .update({
      id: '/theme-provider-reference',
      path: '/theme-provider-reference',
      getParentRoute: () => prestigeDocsLazyRoute,
    } as any)
    .lazy(() =>
      import('./routes/(prestige)/docs.theme-provider-reference.lazy').then(
        (d) => d.Route,
      ),
    )
const prestigeDocsTailwindRoute = prestigeDocsTailwindRouteImport
  .update({
    id: '/tailwind',
    path: '/tailwind',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.tailwind.lazy').then((d) => d.Route),
  )
const prestigeDocsStorageRoute = prestigeDocsStorageRouteImport
  .update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.storage.lazy').then((d) => d.Route),
  )
const prestigeDocsMultiThemingRoute = prestigeDocsMultiThemingRouteImport
  .update({
    id: '/multi-theming',
    path: '/multi-theming',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.multi-theming.lazy').then((d) => d.Route),
  )
const prestigeDocsHydrationRoute = prestigeDocsHydrationRouteImport
  .update({
    id: '/hydration',
    path: '/hydration',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.hydration.lazy').then((d) => d.Route),
  )
const prestigeDocsGetStartedRoute = prestigeDocsGetStartedRouteImport
  .update({
    id: '/get-started',
    path: '/get-started',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.get-started.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof prestigeDocsLazyRouteWithChildren
  '/docs/get-started': typeof prestigeDocsGetStartedRoute
  '/docs/hydration': typeof prestigeDocsHydrationRoute
  '/docs/multi-theming': typeof prestigeDocsMultiThemingRoute
  '/docs/storage': typeof prestigeDocsStorageRoute
  '/docs/tailwind': typeof prestigeDocsTailwindRoute
  '/docs/theme-provider-reference': typeof prestigeDocsThemeProviderReferenceRoute
  '/docs/use-theme-reference': typeof prestigeDocsUseThemeReferenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof prestigeDocsLazyRouteWithChildren
  '/docs/get-started': typeof prestigeDocsGetStartedRoute
  '/docs/hydration': typeof prestigeDocsHydrationRoute
  '/docs/multi-theming': typeof prestigeDocsMultiThemingRoute
  '/docs/storage': typeof prestigeDocsStorageRoute
  '/docs/tailwind': typeof prestigeDocsTailwindRoute
  '/docs/theme-provider-reference': typeof prestigeDocsThemeProviderReferenceRoute
  '/docs/use-theme-reference': typeof prestigeDocsUseThemeReferenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(prestige)/docs': typeof prestigeDocsLazyRouteWithChildren
  '/(prestige)/docs/get-started': typeof prestigeDocsGetStartedRoute
  '/(prestige)/docs/hydration': typeof prestigeDocsHydrationRoute
  '/(prestige)/docs/multi-theming': typeof prestigeDocsMultiThemingRoute
  '/(prestige)/docs/storage': typeof prestigeDocsStorageRoute
  '/(prestige)/docs/tailwind': typeof prestigeDocsTailwindRoute
  '/(prestige)/docs/theme-provider-reference': typeof prestigeDocsThemeProviderReferenceRoute
  '/(prestige)/docs/use-theme-reference': typeof prestigeDocsUseThemeReferenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/get-started'
    | '/docs/hydration'
    | '/docs/multi-theming'
    | '/docs/storage'
    | '/docs/tailwind'
    | '/docs/theme-provider-reference'
    | '/docs/use-theme-reference'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/docs/get-started'
    | '/docs/hydration'
    | '/docs/multi-theming'
    | '/docs/storage'
    | '/docs/tailwind'
    | '/docs/theme-provider-reference'
    | '/docs/use-theme-reference'
  id:
    | '__root__'
    | '/'
    | '/(prestige)/docs'
    | '/(prestige)/docs/get-started'
    | '/(prestige)/docs/hydration'
    | '/(prestige)/docs/multi-theming'
    | '/(prestige)/docs/storage'
    | '/(prestige)/docs/tailwind'
    | '/(prestige)/docs/theme-provider-reference'
    | '/(prestige)/docs/use-theme-reference'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  prestigeDocsLazyRoute: typeof prestigeDocsLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/docs': {
      id: '/(prestige)/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof prestigeDocsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/docs/use-theme-reference': {
      id: '/(prestige)/docs/use-theme-reference'
      path: '/use-theme-reference'
      fullPath: '/docs/use-theme-reference'
      preLoaderRoute: typeof prestigeDocsUseThemeReferenceRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/theme-provider-reference': {
      id: '/(prestige)/docs/theme-provider-reference'
      path: '/theme-provider-reference'
      fullPath: '/docs/theme-provider-reference'
      preLoaderRoute: typeof prestigeDocsThemeProviderReferenceRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/tailwind': {
      id: '/(prestige)/docs/tailwind'
      path: '/tailwind'
      fullPath: '/docs/tailwind'
      preLoaderRoute: typeof prestigeDocsTailwindRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/storage': {
      id: '/(prestige)/docs/storage'
      path: '/storage'
      fullPath: '/docs/storage'
      preLoaderRoute: typeof prestigeDocsStorageRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/multi-theming': {
      id: '/(prestige)/docs/multi-theming'
      path: '/multi-theming'
      fullPath: '/docs/multi-theming'
      preLoaderRoute: typeof prestigeDocsMultiThemingRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/hydration': {
      id: '/(prestige)/docs/hydration'
      path: '/hydration'
      fullPath: '/docs/hydration'
      preLoaderRoute: typeof prestigeDocsHydrationRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/get-started': {
      id: '/(prestige)/docs/get-started'
      path: '/get-started'
      fullPath: '/docs/get-started'
      preLoaderRoute: typeof prestigeDocsGetStartedRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
  }
}

interface prestigeDocsLazyRouteChildren {
  prestigeDocsGetStartedRoute: typeof prestigeDocsGetStartedRoute
  prestigeDocsHydrationRoute: typeof prestigeDocsHydrationRoute
  prestigeDocsMultiThemingRoute: typeof prestigeDocsMultiThemingRoute
  prestigeDocsStorageRoute: typeof prestigeDocsStorageRoute
  prestigeDocsTailwindRoute: typeof prestigeDocsTailwindRoute
  prestigeDocsThemeProviderReferenceRoute: typeof prestigeDocsThemeProviderReferenceRoute
  prestigeDocsUseThemeReferenceRoute: typeof prestigeDocsUseThemeReferenceRoute
}

const prestigeDocsLazyRouteChildren: prestigeDocsLazyRouteChildren = {
  prestigeDocsGetStartedRoute: prestigeDocsGetStartedRoute,
  prestigeDocsHydrationRoute: prestigeDocsHydrationRoute,
  prestigeDocsMultiThemingRoute: prestigeDocsMultiThemingRoute,
  prestigeDocsStorageRoute: prestigeDocsStorageRoute,
  prestigeDocsTailwindRoute: prestigeDocsTailwindRoute,
  prestigeDocsThemeProviderReferenceRoute:
    prestigeDocsThemeProviderReferenceRoute,
  prestigeDocsUseThemeReferenceRoute: prestigeDocsUseThemeReferenceRoute,
}

const prestigeDocsLazyRouteWithChildren =
  prestigeDocsLazyRoute._addFileChildren(prestigeDocsLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  prestigeDocsLazyRoute: prestigeDocsLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
