/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as prestigeDocsUsageRouteImport } from './routes/(prestige)/docs.usage'
import { Route as prestigeDocsReferenceRouteImport } from './routes/(prestige)/docs.reference'
import { Route as prestigeDocsInstallationRouteImport } from './routes/(prestige)/docs.installation'
import { Route as prestigeDocsHydrationRouteImport } from './routes/(prestige)/docs.hydration'
import { Route as prestigeDocsGetStartedRouteImport } from './routes/(prestige)/docs.get-started'

const prestigeDocsLazyRouteImport = createFileRoute('/(prestige)/docs')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const prestigeDocsLazyRoute = prestigeDocsLazyRouteImport
  .update({
    id: '/(prestige)/docs',
    path: '/docs',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(prestige)/docs.lazy').then((d) => d.Route))
const prestigeDocsUsageRoute = prestigeDocsUsageRouteImport
  .update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.usage.lazy').then((d) => d.Route),
  )
const prestigeDocsReferenceRoute = prestigeDocsReferenceRouteImport
  .update({
    id: '/reference',
    path: '/reference',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.reference.lazy').then((d) => d.Route),
  )
const prestigeDocsInstallationRoute = prestigeDocsInstallationRouteImport
  .update({
    id: '/installation',
    path: '/installation',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.installation.lazy').then((d) => d.Route),
  )
const prestigeDocsHydrationRoute = prestigeDocsHydrationRouteImport
  .update({
    id: '/hydration',
    path: '/hydration',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.hydration.lazy').then((d) => d.Route),
  )
const prestigeDocsGetStartedRoute = prestigeDocsGetStartedRouteImport
  .update({
    id: '/get-started',
    path: '/get-started',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.get-started.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof prestigeDocsLazyRouteWithChildren
  '/docs/get-started': typeof prestigeDocsGetStartedRoute
  '/docs/hydration': typeof prestigeDocsHydrationRoute
  '/docs/installation': typeof prestigeDocsInstallationRoute
  '/docs/reference': typeof prestigeDocsReferenceRoute
  '/docs/usage': typeof prestigeDocsUsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof prestigeDocsLazyRouteWithChildren
  '/docs/get-started': typeof prestigeDocsGetStartedRoute
  '/docs/hydration': typeof prestigeDocsHydrationRoute
  '/docs/installation': typeof prestigeDocsInstallationRoute
  '/docs/reference': typeof prestigeDocsReferenceRoute
  '/docs/usage': typeof prestigeDocsUsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(prestige)/docs': typeof prestigeDocsLazyRouteWithChildren
  '/(prestige)/docs/get-started': typeof prestigeDocsGetStartedRoute
  '/(prestige)/docs/hydration': typeof prestigeDocsHydrationRoute
  '/(prestige)/docs/installation': typeof prestigeDocsInstallationRoute
  '/(prestige)/docs/reference': typeof prestigeDocsReferenceRoute
  '/(prestige)/docs/usage': typeof prestigeDocsUsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/get-started'
    | '/docs/hydration'
    | '/docs/installation'
    | '/docs/reference'
    | '/docs/usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/docs/get-started'
    | '/docs/hydration'
    | '/docs/installation'
    | '/docs/reference'
    | '/docs/usage'
  id:
    | '__root__'
    | '/'
    | '/(prestige)/docs'
    | '/(prestige)/docs/get-started'
    | '/(prestige)/docs/hydration'
    | '/(prestige)/docs/installation'
    | '/(prestige)/docs/reference'
    | '/(prestige)/docs/usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  prestigeDocsLazyRoute: typeof prestigeDocsLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/docs': {
      id: '/(prestige)/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof prestigeDocsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/docs/usage': {
      id: '/(prestige)/docs/usage'
      path: '/usage'
      fullPath: '/docs/usage'
      preLoaderRoute: typeof prestigeDocsUsageRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/reference': {
      id: '/(prestige)/docs/reference'
      path: '/reference'
      fullPath: '/docs/reference'
      preLoaderRoute: typeof prestigeDocsReferenceRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/installation': {
      id: '/(prestige)/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof prestigeDocsInstallationRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/hydration': {
      id: '/(prestige)/docs/hydration'
      path: '/hydration'
      fullPath: '/docs/hydration'
      preLoaderRoute: typeof prestigeDocsHydrationRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
    '/(prestige)/docs/get-started': {
      id: '/(prestige)/docs/get-started'
      path: '/get-started'
      fullPath: '/docs/get-started'
      preLoaderRoute: typeof prestigeDocsGetStartedRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
  }
}

interface prestigeDocsLazyRouteChildren {
  prestigeDocsGetStartedRoute: typeof prestigeDocsGetStartedRoute
  prestigeDocsHydrationRoute: typeof prestigeDocsHydrationRoute
  prestigeDocsInstallationRoute: typeof prestigeDocsInstallationRoute
  prestigeDocsReferenceRoute: typeof prestigeDocsReferenceRoute
  prestigeDocsUsageRoute: typeof prestigeDocsUsageRoute
}

const prestigeDocsLazyRouteChildren: prestigeDocsLazyRouteChildren = {
  prestigeDocsGetStartedRoute: prestigeDocsGetStartedRoute,
  prestigeDocsHydrationRoute: prestigeDocsHydrationRoute,
  prestigeDocsInstallationRoute: prestigeDocsInstallationRoute,
  prestigeDocsReferenceRoute: prestigeDocsReferenceRoute,
  prestigeDocsUsageRoute: prestigeDocsUsageRoute,
}

const prestigeDocsLazyRouteWithChildren =
  prestigeDocsLazyRoute._addFileChildren(prestigeDocsLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  prestigeDocsLazyRoute: prestigeDocsLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
