/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as prestigeDocsShowcaseRouteImport } from './routes/(prestige)/docs.showcase'

const prestigeDocsLazyRouteImport = createFileRoute('/(prestige)/docs')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const prestigeDocsLazyRoute = prestigeDocsLazyRouteImport
  .update({
    id: '/(prestige)/docs',
    path: '/docs',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(prestige)/docs.lazy').then((d) => d.Route))
const prestigeDocsShowcaseRoute = prestigeDocsShowcaseRouteImport
  .update({
    id: '/showcase',
    path: '/showcase',
    getParentRoute: () => prestigeDocsLazyRoute,
  } as any)
  .lazy(() =>
    import('./routes/(prestige)/docs.showcase.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof prestigeDocsLazyRouteWithChildren
  '/docs/showcase': typeof prestigeDocsShowcaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof prestigeDocsLazyRouteWithChildren
  '/docs/showcase': typeof prestigeDocsShowcaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(prestige)/docs': typeof prestigeDocsLazyRouteWithChildren
  '/(prestige)/docs/showcase': typeof prestigeDocsShowcaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docs' | '/docs/showcase'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs' | '/docs/showcase'
  id: '__root__' | '/' | '/(prestige)/docs' | '/(prestige)/docs/showcase'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  prestigeDocsLazyRoute: typeof prestigeDocsLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/docs': {
      id: '/(prestige)/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof prestigeDocsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(prestige)/docs/showcase': {
      id: '/(prestige)/docs/showcase'
      path: '/showcase'
      fullPath: '/docs/showcase'
      preLoaderRoute: typeof prestigeDocsShowcaseRouteImport
      parentRoute: typeof prestigeDocsLazyRoute
    }
  }
}

interface prestigeDocsLazyRouteChildren {
  prestigeDocsShowcaseRoute: typeof prestigeDocsShowcaseRoute
}

const prestigeDocsLazyRouteChildren: prestigeDocsLazyRouteChildren = {
  prestigeDocsShowcaseRoute: prestigeDocsShowcaseRoute,
}

const prestigeDocsLazyRouteWithChildren =
  prestigeDocsLazyRoute._addFileChildren(prestigeDocsLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  prestigeDocsLazyRoute: prestigeDocsLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
